#!/bin/bash

# basic workflow for combined structure function
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

COMP="0"

FIELD="mag"
TITLE='$B_x$'

#------------------------

NUM_WARMUP=1000
NUM_SAMPLES=10000
SEED=1

MIN_SCALE="5"
MAX_SCALE="120"

#-------------------------------------------------

FLOW="M05MA01"

#-------------------------------------------------

echo \
w4t-average-structure-function \
    ../data/${FLOW}/${FLOW}_0???-${FIELD}_${COMP}-direct-structure-function.hdf \
    ../data/${FLOW}/${FLOW}_aved-${FIELD}_${COMP}-direct-structure-function.hdf \
    --verbose \
|| exit 1

#---------------------------------------------

echo \
w4t-sample-structure-function-ansatz \
    "../data/${FLOW}/${FLOW}_aved-${FIELD}_${COMP}-direct-structure-function.hdf" \
    "../data/${FLOW}/${FLOW}_aved-${FIELD}_${COMP}-direct-sample-structure-function-ansatz.hdf" \
    --num-warmup $NUM_WARMUP \
    --num-samples $NUM_SAMPLES \
    --max-scale $MAX_SCALE \
    --seed $SEED \
    --verbose \
|| exit 1

#echo \
w4t-plot-structure-function-ansatz \
    "../data/${FLOW}/${FLOW}_aved-${FIELD}_${COMP}-direct-structure-function.hdf" \
    "../data/${FLOW}/${FLOW}_aved-${FIELD}_${COMP}-direct-sample-structure-function-ansatz.hdf" \
    --max-num-samples 100 \
    --output-dir ../data/${FLOW}/ \
    --tag ${FIELD}_${COMP}-${FLOW}_aved-direct \
    --verbose \
|| exit 1
