#!/bin/bash

# basic workflow
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

FLOW=$1
SNAP=$2

FIELD=$3

TITLE="${FIELD}"

#------------------------

NUM_WARMUP=1000
NUM_SAMPLES=10000
SEED=1

MIN_SCALE="5"
MAX_SCALE="120"

#-------------------------------------------------

TAG="${FLOW}_${SNAP}"

#---

OUTDIR="../data/${FLOW}"

#---

BASE="${OUTDIR}/${TAG}"

#---------------------------------------------

# compute structure function

echo \
w4t-structure-function \
    ${BASE}.hdf \
    ${BASE}-${FIELD}-structure-function.hdf \
    ${FIELD} \
    --max-edgelength 512 \
    --index 1 2 3 4 \
    --Verbose \
|| exit 1

#---

echo \
w4t-scaling-exponent \
    ${BASE}-${FIELD}-structure-function.hdf \
    ${BASE}-${FIELD}-scaling-exponent.hdf \
    --min-scale $MIN_SCALE \
    --max-scale $MAX_SCALE \
    --degree 1 \
    --verbose \
|| exit 1

#-------

echo \
w4t-structure-function \
    ${BASE}.hdf \
    ${BASE}-${FIELD}-direct-structure-function.hdf \
    ${FIELD} \
    --max-edgelength 512 \
    --direct-increment 16 \
    --index 1 2 3 4 \
    --direct \
    --Verbose \
|| exit 1

#---

echo \
w4t-scaling-exponent \
    ${BASE}-${FIELD}-direct-structure-function.hdf \
    ${BASE}-${FIELD}-direct-scaling-exponent.hdf \
    --min-scale $MIN_SCALE \
    --max-scale $MAX_SCALE \
    --degree 1 \
    --verbose \
|| exit 1

#------------------------

# denoise to identify coherent structures

#echo \
w4t-denoise \
    ${BASE}.hdf \
    ${BASE}-${FIELD}-denoise.hdf \
    ${FIELD} \
    --max-edgelength 512 \
    --wavelet haar \
    --quantile 0.30 \
    --threshold 3.0 \
    --max-scale 256 \
    --verbose \
|| exit 1

#-----------

# compute structure function of denoised flow

echo \
w4t-structure-function \
    ${BASE}-${FIELD}-denoise.hdf \
    ${BASE}-${FIELD}-denoise-structure-function.hdf \
    ${FIELD} \
    --max-edgelength 512 \
    --index 1 2 3 4 \
    --Verbose \
|| exit 1

#-----------

echo \
w4t-scaling-exponent \
    ${BASE}-${FIELD}-denoise-structure-function.hdf \
    ${BASE}-${FIELD}-denoise-scaling-exponent.hdf \
    --min-scale $MIN_SCALE \
    --max-scale $MAX_SCALE \
    --degree 1 \
    --verbose \
|| exit 1

#-----------

# identify structures as separate sets of pixels

#echo \
w4t-structures \
    ${BASE}-${FIELD}-denoise.hdf \
    ${BASE}-${FIELD}-denoise-structures.hdf \
    ${FIELD} \
    --wavelet haar \
    --quantile 0.68 \
    --max-edgelength 256 \
    --structure-threshold 3.0 \
    --num-proc 4 \
    --verbose \
|| exit 1

#------------------------

# denoise to remove coherent structures

echo \
w4t-denoise \
    ${BASE}.hdf \
    ${BASE}-${FIELD}-smooth.hdf \
    ${FIELD} \
    --max-edgelength 512 \
    --wavelet haar \
    --threshold 3.0 \
    --smooth \
    --max-scale 256 \
    --verbose \
|| exit 1

#-----------

# compute structure function of smoothed flow

echo \
w4t-structure-function \
    ${BASE}-${FIELD}-smooth.hdf \
    ${BASE}-${FIELD}-smooth-structure-function.hdf \
    ${FIELD} \
    --max-edgelength 512 \
    --index 1 2 3 4 \
    --Verbose \
|| exit 1

#-----------

echo \
w4t-scaling-exponent \
    ${BASE}-${FIELD}-smooth-structure-function.hdf \
    ${BASE}-${FIELD}-smooth-scaling-exponent.hdf \
    --min-scale $MIN_SCALE \
    --max-scale $MAX_SCALE \
    --degree 1 \
    --verbose \
|| exit 1

#---------------------------------------------

# plot the structure functions

echo \
w4t-plot-structure-function \
    --title "$FLOW $SNAP $TITLE" \
    --source    'wavelet'   ${BASE}-${FIELD}-structure-function.hdf \
    --linestyle 'wavelet'   'none' \
    --marker    'wavelet'   'o' \
    --source    'direct'    ${BASE}-${FIELD}-direct-structure-function.hdf \
    --linestyle 'direct'    'none' \
    --marker    'direct'    '^' \
    --output-dir $OUTDIR \
    --tag wavelet_vs_direct-${FIELD}-$TAG \
    --Verbose \
|| exit 1

#---

echo \
w4t-plot-structure-function \
    --title "$FLOW $SNAP $TITLE" \
    --source       'full'    ${BASE}-${FIELD}-structure-function.hdf \
    --scaling-poly 'full'    ${BASE}-${FIELD}-scaling-exponent.hdf \
    --linestyle    'full'    'none' \
    --marker       'full'    'o' \
    --source       'denoise' ${BASE}-${FIELD}-denoise-structure-function.hdf \
    --scaling-poly 'denoise' ${BASE}-${FIELD}-denoise-scaling-exponent.hdf \
    --linestyle    'denoise' 'dashed' \
    --marker       'denoise' 's' \
    --source       'smooth'  ${BASE}-${FIELD}-smooth-structure-function.hdf \
    --scaling-poly 'smooth'  ${BASE}-${FIELD}-smooth-scaling-exponent.hdf \
    --linestyle    'smooth'  'dotted' \
    --marker       'smooth'  '^' \
    --output-dir $OUTDIR \
    --tag ${FIELD}-$TAG \
    --Verbose \
|| exit 1

#    --rescale \

#---------------------------------------------

echo \
w4t-sample-structure-function-ansatz \
    ${BASE}-${FIELD}-structure-function.hdf \
    ${BASE}-${FIELD}-sample-structure-function-ansatz.hdf \
    --num-warmup $NUM_WARMUP \
    --num-samples $NUM_SAMPLES \
    --max-scale $MAX_SCALE \
    --seed $SEED \
    --verbose \
|| exit 1

echo \
w4t-plot-structure-function-ansatz \
    ${BASE}-${FIELD}-structure-function.hdf \
    ${BASE}-${FIELD}-sample-structure-function-ansatz.hdf \
    --max-num-samples 100 \
    --output-dir $OUTDIR \
    --tag ${FIELD}-$TAG \
    --verbose \
|| exit 1

#---

echo \
w4t-sample-structure-function-ansatz \
    ${BASE}-${FIELD}-direct-structure-function.hdf \
    ${BASE}-${FIELD}-direct-sample-structure-function-ansatz.hdf \
    --num-warmup $NUM_WARMUP \
    --num-samples $NUM_SAMPLES \
    --max-scale $MAX_SCALE \
    --seed $SEED \
    --verbose \
|| exit 1

echo \
w4t-plot-structure-function-ansatz \
    ${BASE}-${FIELD}-direct-structure-function.hdf \
    ${BASE}-${FIELD}-direct-sample-structure-function-ansatz.hdf \
    --max-num-samples 100 \
    --output-dir $OUTDIR \
    --tag ${FIELD}-${TAG}-direct \
    --verbose \
|| exit 1
