#!/bin/bash

# test basic workflows
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

for FIELD in "mag" "vel" "dens"
do

        ./scaling M05MA01 0050 $FIELD || exit 1
        ./scaling M05MA01 0060 $FIELD || exit 1
        ./scaling M05MA01 0070 $FIELD || exit 1
        ./scaling M05MA01 0080 $FIELD || exit 1
        ./scaling M05MA01 0090 $FIELD || exit 1

        ./scaling M05MA05 0050 $FIELD || exit 1

        ./scaling M05MA10 0050 $FIELD || exit 1

        ./scaling M10MA01 0050 $FIELD || exit 1

        ./scaling M10MA05 0050 $FIELD || exit 1

        ./scaling M10MA10 0050 $FIELD || exit 1

done
