#!/bin/bash

# test basic workflows
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

for FIELD in "mag" "vel"
do

    for COMP in "0" "1" "2"
    do

        ./scaling M05MA01 0050 $FIELD $COMP
        ./scaling M05MA01 0060 $FIELD $COMP
        ./scaling M05MA01 0070 $FIELD $COMP
        ./scaling M05MA01 0080 $FIELD $COMP
        ./scaling M05MA01 0090 $FIELD $COMP

        ./scaling M05MA05 0050 $FIELD $COMP

        ./scaling M05MA10 0050 $FIELD $COMP

        ./scaling M10MA01 0050 $FIELD $COMP

        ./scaling M10MA05 0050 $FIELD $COMP

        ./scaling M10MA10 0050 $FIELD $COMP

    done
done
