#!/bin/bash

# a quick script to average structure functions over snapshots and then make a plot
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

FLOWS=()

#for M in "05" "2" "4" "10"
for M in "05"
do
#    for MA in "01" "05" "1" "2" "4" "6" "8" "10"
    for MA in "01" "05" "2" "4" "6" "8"
    do
        FLOWS+=(M${M}MA${MA})
    done
done

#-------------------------------------------------

for FLOW in ${FLOWS[@]}
do
#    for FIELD in dens vel vort mag curr
    for FIELD in vel vort mag curr
    do
        for METHOD in dsf wsf
        do
            for THR in 01d00 02d00 03d00 04d00 05d00 10d00
            do
                for SMOOTH in "" "-smooth"
                do

                    ARGS=""
                    for SNAP in $(seq 50 100)
                    do
                        ARGS="$ARGS ${FLOW}/*${SNAP}/${FLOW}_*${SNAP}_${FIELD}_${METHOD}_denoise-${THR}${SMOOTH}.hdf"
                    done

                    TARGET="${FLOW}/${FLOW}_avrg_${FIELD}_${METHOD}_denoise-${THR}${SMOOTH}.hdf"

#                    echo \
                    w4t-average-structure-function \
                        $ARGS \
                        $TARGET \
                        --verbose \
                    || exit 1

#                    echo \
                    w4t-plot-structure-function \
                        --source average $TARGET \
                        --linestyle average solid \
                        --marker average o \
                        --title "$FLOW $FIELD $METHOD average" \
                        --Verbose \
                        --output-dir $FLOW \
                        --tag ${FLOW}_avrg_${FIELD}_${METHOD}_denoise-${THR}${SMOOTH} \
                    || exit 1

#                        --normalize-scale 128 \

                done
            done
        done
    done
done
