#!/bin/bash

# a simple script to launch scripts
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

FLOWS=()

#for M in "05" "2" "4" "10"
for M in "2"
do
#    for MA in "01" "05" "1" "2" "4" "6" "8" "10"
    for MA in "01"
    do
        FLOWS+=(M${M}MA${MA})
    done
done

#FLOWS+=(M6MA01)
#FLOWS+=(M6MA05)
#FLOWS+=(M6MA1)

#-------------------------------------------------

for FLOW in ${FLOWS[@]}
do
    for SNAP in $(seq 50 100)
    do
        for FIELD in dens vel vort mag curr
	do
	    for METHOD in dsf wsf
            do
                for SCRIPT in $(ls ${FLOW}/*${SNAP}/${FLOW}_*${SNAP}_${FIELD}_${METHOD}_denoise-*.sh 2> /dev/null)
                do
                    echo "launching: $SCRIPT"

#                    echo \
                    qsub ${SCRIPT} || exit 1

                done
	    done
	done
    done
done
