#!/bin/bash

# a quick script to generate some summary plots
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

FLOWS=()

#for M in "05" "2" "4" "10"
for M in "05"
do
    for MA in "01" "05" "1" "2" "4" "6" "8" "10"
    do
        FLOWS+=(M${M}MA${MA})
    done
done

#-------------------------------------------------

for FLOW in ${FLOWS[@]}
do
#    for FIELD in dens vel vort mag curr
    for FIELD in vel vort mag curr
    do
        for METHOD in dsf wsf
        do
            for THR in 01d00 02d00 03d00 04d00 05d00 10d00
            do
                for SMOOTH in "" "-smooth"
                do

                ARGS=""
                for SNAP in $(seq 50 100)
                do
                    ARGS="$ARGS --source $SNAP ${FLOW}/*${SNAP}/${FLOW}_*${SNAP}_${FIELD}_${METHOD}_denoise-${THR}${SMOOTH}.hdf"
                    ARGS="$ARGS --linestyle $SNAP solid"
                    ARGS="$ARGS --marker $SNAP o"
                    ARGS="$ARGS --alpha $SNAP 0.05"
                done

#                echo \
                w4t-plot-structure-function \
                    $ARGS \
                    --title "$FLOW $FIELD $METHOD" \
                    --Verbose \
                    --output-dir $FLOW \
                    --tag ${FLOW}_${FIELD}_${METHOD}_denoise-${THR}${SMOOTH} \
                || exit 1

#                    --normalize-scale 128 \

                done
            done
        done
    done
done
