#!/bin/bash

# a quick script to fit the average structure functions
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

FLOWS=()

#for M in "05" "2" "4" "10"
for M in "05"
do
    for MA in "01" "05" "1" "2" "4" "6" "8" "10"
    do
        FLOWS+=(M${M}MA${MA})
    done
done

#-------------------------------------------------

for FLOW in ${FLOWS[@]}
do
#    for FIELD in dens vel vort mag curr
    for FIELD in vel vort mag curr
    do
        for METHOD in dsf wsf
        do
            for THR in 01d00 02d00 03d00 04d00 05d00 10d00
            do
                for SMOOTH in "" "-smooth"
                do

                    STRCFNC="${FLOW}/${FLOW}_avrg_${FIELD}_${METHOD}_denoise-${THR}${SMOOTH}.hdf"
                    SAMPLES="${FLOW}/${FLOW}_avrg_${FIELD}_${METHOD}_denoise-${THR}${SMOOTH}-ansatz.hdf"

                    #---

#                    echo \
                    w4t-sample-structure-function-ansatz \
                        $STRCFNC \
                        $SAMPLES \
                        --min-scale 1 \
                        --max-scale 512 \
                        --num-warmup 10000 \
                        --num-samples 10000 \
                        --seed 1234 \
                        --verbose \
                    || exit 1

                    #---

#                    echo \
                    w4t-plot-structure-function-ansatz \
                        $STRCFNC \
                        $SAMPLES \
                        8 16 32 64 128 \
                        --title "$FLOW $FIELD $METHOD" \
                        --max-num-samples 500 \
                        --output-dir ${FLOW} \
                        --tag ${FLOW}_avrg_${FIELD}_${METHOD}_denoise-${THR}${SMOOTH} \
                        --Verbose \
                    || exit 1

                    #---

#                    for p in $(seq 1 6)
#                    do
#
##                        echo \
#                        w4t-corner \
#                            $SAMPLES \
#                            --fields amp bh bl nh nl sh sl xi \
#                            --log amp \
#                            --root posterior_$p \
#                            --title "$FLOW $FIELD $METHOD average p=$p" \
#                            --output-dir ${FLOW} \
#                            --tag ${FLOW}_avrg_${FIELD}_${METHOD}_denoise-${THR}${SMOOTH}_p$p \
#                            --verbose \
#                        || exit 1
#
#                    done

                done
            done
        done
    done
done
