#!/bin/bash

#---

LEVELS="0 2 4 6"
THRESHOLDS="0 1 2 3 4 5 10"
QUANTILES="10 60 99"

#---

for WAVELET in "haar" ### FIXME! try a few other wavelets as well?
do

    for SNAP in "0050"
    do

        for FLOW in "M05MA01" "M05MA10" "M10MA10"
        do
            SOURCE="../../data/${FLOW}/${FLOW}_${SNAP}.hdf"

            for FIELD in "dens" "vel" "mag"
            do

#                echo \
                w4t-structure-function \
                    ${SOURCE} \
                    ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-dsf.hdf \
                    $FIELD \
                    --index 1 2 3 4 5 6 \
                    --max-edgelength 512 \
                    --wavelet $WAVELET \
                    --direct --direct-increment 16 \
                    --Verbose \
                || exit 1

#                echo \
                w4t-plot-structure-function \
                    --source $FIELD ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-dsf.hdf \
                    --tag ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-dsf \
                    --Verbose \
                || exit 1

                for level in $LEVELS
                do

                    echo \
                    w4t-plot-flow \
                        ${SOURCE} \
                        plot plot_coeff hist hist_coeff \
                        ${FIELD} \
                        --max-edgelength 128 \
                        --levels $level $level $level \
                        --wavelet ${WAVELET} \
                        --verbose \
                        --tag ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-$level \
                    || exit 1

                done

                #---

                for thr in $THRESHOLDS
                do

#                    echo \
                    w4t-structure-function \
                        ${SOURCE} \
                        ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-dsf-denoise-0${thr}d00-smooth.hdf \
                        $FIELD \
                        --index 1 2 3 4 5 6 \
                        --max-edgelength 512 \
                        --wavelet ${WAVELET} \
                        --threshold $thr \
                        --smooth \
                        --direct --direct-increment 16 \
                        --Verbose \
                    || exit 1

#                    echo \
                    w4t-plot-structure-function \
                        --source $FIELD ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-dsf-denoise-0${thr}d00-smooth.hdf \
                        --tag ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-dsf-denoise-0${thr}d00-smooth \
                        --Verbose \
                    || exit 1

                    for level in $LEVELS
                    do

                        echo \
                        w4t-plot-flow \
                            ${SOURCE} \
                            plot plot_coeff hist hist_coeff \
                            ${FIELD} \
                            --wavelet ${WAVELET} \
                            --threshold $thr \
                            --smooth \
                            --max-edgelength 128 \
                            --levels $level $level $level \
                            --verbose \
                            --tag ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-${level}-denoise-0${thr}d00-smooth \
                        || exit 1

                    done
                done

                #---

                for thr in $THRESHOLDS
                do
                    for q in $QUANTILES
                    do

#                        echo \
                        w4t-structure-function \
                            ${SOURCE} \
                            ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-dsf-quantile-0d${q}-denoise-0${thr}d00-smooth.hdf \
                            $FIELD \
                            --index 1 2 3 4 5 6 \
                            --max-edgelength 512 \
                            --wavelet ${WAVELET} \
                            --threshold $thr \
                            --quantile 0.${q} \
                            --smooth \
                            --direct --direct-increment 16 \
                            --Verbose \
                        || exit 1

#                        echo \
                        w4t-plot-structure-function \
                            --source $FIELD ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-dsf-quantile-0d${q}-denoise-0${thr}d00-smooth.hdf \
                            --tag ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-dsf-quantile-0d${q}-denoise-0${thr}d00-smooth \
                            --Verbose \
                        || exit 1

                        for level in $LEVELS
                        do

                            echo \
                            w4t-plot-flow \
                                ${SOURCE} \
                                plot plot_coeff hist hist_coeff \
                                ${FIELD} \
                                --wavelet ${WAVELET} \
                                --quantile 0.${q} \
                                --threshold $thr \
                                --smooth \
                                --max-edgelength 128 \
                                --levels $level $level $level \
                                --verbose \
                                --tag ${FLOW}_${SNAP}-${FIELD}-${WAVELET}-${level}-quantile-0d${q}-denoise-0${thr}d00-smooth \
                            || exit 1

                        done
                    done
                done
            done
        done
    done
done
