#!/bin/bash

# a simple script to iterate over data and schedule workflows
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

declare -A SNAPS

SNAPS['M05MA01']=$(seq -f "%04g" 50 10 90)

for SNAP in M05MA05  M05MA10  M10MA01  M10MA05  M10MA10
do
    SNAPS[$SNAP]=0050
done

#-------------------------------------------------

for FLOW in ${!SNAPS[@]}
do

    for SNAP in ${SNAPS[$FLOW]}
    do

        # schedule workflows

#        echo \
        ./schedule \
            $FLOW $SNAP \
            --output-dir $PWD/${FLOW}/${SNAP} \
            --data-dir ../data/$FLOW \
            --direct-increment 16 \
            --max-edgelength 512 \
            --Verbose \
        || exit 1

        #---

        # launch workflows

#        echo \
        /usr/bin/time -v \
        $PWD/${FLOW}/${SNAP}/sf-${FLOW}_${SNAP}.sh \
        || exit 1

#        echo \
        /usr/bin/time -v \
        $PWD/${FLOW}/${SNAP}/plot-sf-${FLOW}_${SNAP}.sh \
        || exit 1

    done
done
