#!/bin/zsh

#---

rtol=5e-2 # required to get the sampler to find anything reasonable. May need to anneal to burn in correctly...
num_grid=51

min_scale="2.0e-4" 
max_scale="4.998e-1"

#---

for field in vel # mag
do

    for long_or_trsv in trsv long
    do

        OUTDIR="fits/${field}-$long_or_trsv"
        mkdir -p $OUTDIR

        #---

        echo \
        ./plot-structure-function \
            strufu_10k/${field}/EXTREME_Turb_hdf5_plt_cnt_*_downsampled_sf_${field}s.dat \
            --index 1 --index 2 --index 3 --index 4 --index 5 --index 6 --index 7 --index 8 --index 9 --index 10 \
            --long-or-trsv $long_or_trsv \
            --min-scale $min_scale \
            --max-scale $max_scale \
            --logspace-scales $num_grid \
            --min-rtol $rtol \
            --output-dir $OUTDIR \
            --tag ${field}-${long_or_trsv} \
            --title "$field $long_or_trsv" \
            --verbose \
        || exit 1

        for index in 01 02 03 04 05 06 07 08 09 10
        do

            echo ">>> SAMPLING ${field} ${long_or_trsv} ${index}"

            outpath="${OUTDIR}/structure-function-ansatz-samples-${field}-${long_or_trsv}-${index}.hdf"

            echo \
            ./sample-structure-function-ansatz \
                strufu_10k/${field}/EXTREME_Turb_hdf5_plt_cnt_*_downsampled_sf_${field}s.dat \
                --index ${index} \
                --long-or-trsv $long_or_trsv \
                --min-scale $min_scale \
                --max-scale $max_scale \
                --logspace-scales $num_grid \
                --min-rtol $rtol \
                --outpath $outpath \
                --seed 1 --seed 2 --seed 3 --seed 4 --seed 5 \
                --num-warmup 500 \
                --num-samples 50000 \
                --num-segs 5 \
                --verbose \
            || exit 1

#                --seed 6 --seed 7 --seed 8 --seed 9 \

            echo \
            w4t-corner \
                $outpath \
                -f amp xi s1 b1 n1 s2 b2 n2 s3 b3 n3 \
                --log amp --log s1 --log s2 --log s3 \
                --root posterior \
                --title "$field $long_or_trsv $index" \
                --output-dir $OUTDIR \
                --tag ${field}-${long_or_trsv}-${index} \
                --verbose \
            || exit 1 

            echo \
            w4t-corner \
                $outpath \
                -f amp xi s1 b1 n1 s2 b2 n2 s3 b3 n3 \
                --log amp --log s1 --log s2 --log s3 \
                --root prior \
                --title "$field $long_or_trsv $index" \
                --output-dir $OUTDIR \
                --tag ${field}-${long_or_trsv}-${index}-prior \
                --verbose \
            || exit 1

        done
    done
done

#---

field=vel
long_or_trsv=trsv

OUTDIR="fits/${field}-$long_or_trsv"

#echo \
./plot-structure-function-ansatz \
    $OUTDIR/structure-function-ansatz-samples-${field}-${long_or_trsv}-??.hdf \
    --mach fits/vel-${long_or_trsv}/structure-function-ansatz-samples-vel-${long_or_trsv}-02.hdf \
    --vband C0 '/' 3e-4 6e-4 \
    --vband C1 '\' 4e-3 8e-3 \
    --vband C2 'x' 7e-2 14e-2 \
    --output-dir $OUTDIR \
    --tag ${field}-${long_or_trsv} \
    --long-or-trsv $long_or_trsv \
    --field $field \
    --verbose \
|| exit 1

#    --title "$field $long_or_trsv" \

long_or_trsv=long
            
OUTDIR="fits/${field}-$long_or_trsv"
            
#echo \ 
./plot-structure-function-ansatz \
    $OUTDIR/structure-function-ansatz-samples-${field}-${long_or_trsv}-??.hdf \
    --mach fits/vel-${long_or_trsv}/structure-function-ansatz-samples-vel-${long_or_trsv}-02.hdf \
    --vband C0 '/' 3e-4 6e-4 \
    --vband C1 '\' 7e-3 14e-3 \
    --vband C2 'x' 6e-2 12e-2 \
    --output-dir $OUTDIR \
    --tag ${field}-${long_or_trsv} \
    --long-or-trsv $long_or_trsv \
    --field $field \
    --verbose \
|| exit 1
            
#    --title "$field $long_or_trsv" \

#---

field=mag
for long_or_trsv in trsv long
    do

    OUTDIR="fits/${field}-$long_or_trsv"

#    echo \
    ./plot-structure-function-ansatz \
        $OUTDIR/structure-function-ansatz-samples-${field}-${long_or_trsv}-??.hdf \
        --mach fits/vel-${long_or_trsv}/structure-function-ansatz-samples-vel-${long_or_trsv}-02.hdf \
        --alven fits/mag-${long_or_trsv}/structure-function-ansatz-samples-mag-${long_or_trsv}-02.hdf \
        --vband C0 'x' 7e-4 14e-4 \
        --output-dir $OUTDIR \
        --tag ${field}-${long_or_trsv} \
        --long-or-trsv $long_or_trsv \
        --field $field \
        --verbose \
    || exit 1

#        --title "$field $long_or_trsv" \

done
