#!/usr/bin/env python3

"""a script to make plots of the scaling exponent ansatz
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import os

import numpy as np

import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt
plt.rcParams['text.usetex'] = True

from argparse import ArgumentParser

### non-standard libraries
import utils

#-------------------------------------------------

parser = ArgumentParser()

parser.add_argument('she_leveque_posteriors', type=str)
parser.add_argument('independent_posteriors', nargs='*', type=str)

parser.add_argument('--max-num-samples', default=500, type=int)

parser.add_argument('-o', '--output-dir', default='.', type=str)
parser.add_argument('-t', '--tag', default='', type=str)

parser.add_argument('--title', default=None, type=str)

parser.add_argument('-v', '--verbose', default=False, action='store_true')

args = parser.parse_args()

os.makedirs(args.output_dir, exist_ok=True)

if args.tag:
    args.tag = "_"+args.tag

#-------------------------------------------------

# load she-leveque posteriors
post, prior, meta = utils.load_scaling_exponent_samples(args.she_leveque_posteriors, verbose=args.verbose)

indep_post = dict()
for path in args.independent_posteriors:
    p, _, _, m = utils.load_structure_function_samples(path, verbose=args.verbose)
    indep_post[m['index']] = p

#------------------------

fig = plt.figure()
ax = fig.gca()

plt.subplots_adjust(
    left=0.10,
    right=0.95,
    bottom=0.10,
    top=0.90,
)

#---

# plot the full fitted curves

p = np.linspace(0, 11, 101)
num = len(post['C0'])

step = int(np.ceil(num/args.max_num_samples))
i = 0
while i < num:
    ax.plot(
        p,
        utils.scaling_exponent_ansatz(p, post['x'][i], post['C0'][i], post['beta'][i]),
        color='k',
        alpha=0.01,
        zorder=-10,
    )
    i += step

#---

# plot violins

for _p in range(1, 11):

    color = 'C%d' % _p

    # plot the She-Leveque fit

    samp = utils.scaling_exponent_ansatz(_p, post['x'], post['C0'], post['beta'])
    kde_stdv = 1.06 * np.std(samp) / len(samp)**0.2

    grid = np.min(samp), np.max(samp)
    d = 0.5*(grid[1]-grid[0])
    grid = np.linspace(grid[0]-d, grid[1]+d, 101)

    kde = np.sum(
        [np.exp(-0.5*(S-grid)**2/kde_stdv**2)/(2*np.pi*kde_stdv**2)**0.5 for S in samp],
        axis=0,
    )
    kde *= 0.25/np.max(kde)

    ax.fill_betweenx(grid, _p*np.ones_like(grid), _p+kde, color=color, alpha=0.50)

# plot independent violins

for _p, samples in indep_post.items():

    color = 'C%d' % _p

    samp = utils.averaged_logarithmic_derivative_ansatz(
        meta['ref_scale'][0],
        meta['ref_scale'][1],
        samples['amp'],
        samples['xi'],
        samples['s1'],
        samples['b1'],
        samples['n1'],
        samples['s2'],
        samples['b2'],
        samples['n2'],
        samples['s3'],
        samples['b3'],
        samples['n3'],
    )

    kde_stdv = 1.06 * np.std(samp) / len(samp)**0.2

    grid = np.min(samp), np.max(samp)
    d = 0.5*(grid[1]-grid[0])
    grid = np.linspace(grid[0]-d, grid[1]+d, 101)

    kde = np.sum(
        [np.exp(-0.5*(S-grid)**2/kde_stdv**2)/(2*np.pi*kde_stdv**2)**0.5 for S in samp],
        axis=0,
    )
    kde *= 0.25/np.max(kde)

    ax.plot(_p-kde, grid, color=color, alpha=0.50)

#---

ax.set_xlabel('$p$')
ax.set_ylabel(r'$\left< \xi_p \right>_{\ln s}$')

if args.title is not None:
    ax.set_title(args.title)

ax.tick_params(
    left=True,
    right=True,
    top=True,
    bottom=True,
    which='both',
    direction='in',
)

ax.grid(True, which='both')

ax.set_xlim(xmin=p[0], xmax=p[-1])
ax.set_ylim(ymin=0.0)

figname = os.path.join(args.output_dir, 'plot-scaling-exponent-ansatz%s.png' % args.tag)
if args.verbose:
    print('saving: '+figname)
fig.savefig(figname, dpi=200)
plt.close(fig)
