#!/usr/bin/env python3

"""a quick script to sample a structure function ansatz for data based on a very big box
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import numpy as np

from argparse import ArgumentParser

### non-standard libraries
import utils

#-------------------------------------------------

parser = ArgumentParser()

parser.add_argument('dat', nargs='+', type=str,
    help='paths to .dat files that contain structure functions')

parser.add_argument('--index', nargs='+', type=int, required=True,
    help='fit structure functions for these indexes')

parser.add_argument('--min-rtol', default=1e-3, type=float,
    help='set a lower limit on the estimated uncertainty in structure-function data')

parser.add_argument('--num-warmup', default=1000, type=int)
parser.add_argument('--num-samples', default=10000, type=int)
parser.add_argument('--seed', default=[], type=int, action='append', required=True)
parser.add_argument('--num-segs', default=1, type=int)

parser.add_argument('-v', '--verbose', default=False, action='store_true')

parser.add_argument('--outpath', default='sample-structure-function.hdf', type=str)

args = parser.parser_args()

#-------------------------------------------------

posterior, prior = utils.sample_structure_function_ansatz(
    scales,
    mom,
    std,
    num_warmup=args.num_warmup,
    num_samples=args.num_samples,
    seed=args.seed,
    num_segs=args.num_segs,
    verbose=args.verbose,
    **prior_kwargs
)
