#!/usr/bin/env python3

"""a quick script to sample a structure function ansatz for data based on a very big box
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import numpy as np

from argparse import ArgumentParser

### non-standard libraries
import utils

#-------------------------------------------------

parser = ArgumentParser()

parser.add_argument('dat', nargs='+', type=str,
    help='paths to .dat files that contain structure functions')

parser.add_argument('--index', type=int, required=True,
    help='fit structure functions for this index')
parser.add_argument('--long-or-trsv', type=str, required=True,
    help='must be one of either "long" or "trsv"')

parser.add_argument('--min-rtol', default=1e-3, type=float,
    help='set a lower limit on the estimated uncertainty in structure-function data')
parser.add_argument('--min-atol', default=1e-3, type=float)

parser.add_argument('--min-scale', default=0.0, type=float)
parser.add_argument('--max-scale', default=0.5, type=float)

parser.add_argument('--num-warmup', default=1000, type=int)
parser.add_argument('--num-samples', default=10000, type=int)
parser.add_argument('--seed', default=[], type=int, action='append', required=True)
parser.add_argument('--num-segs', default=1, type=int)

parser.add_argument('--prior-kwarg', nargs=2, type=str, default=[], action='append')

parser.add_argument('-v', '--verbose', default=False, action='store_true')
parser.add_argument('-V', '--Verbose', default=False, action='store_true')

parser.add_argument('--outpath', default='sample-structure-function.hdf', type=str)

args = parser.parse_args()

args.prior_kwarg = dict((k, float(v)) for k, v in args.prior_kwarg)

args.verbose |= args.Verbose

#-------------------------------------------------

# load data
scales, mom, stdv = utils.load_structure_function_dat(
    args.dat,
    args.index,
    args.long_or_trsv,
    min_rtol=args.min_rtol,
    min_atol=args.min_atol,
    min_scale=args.min_scale,
    max_scale=args.max_scale,
    verbose=args.Verbose,
)

#------------------------

# sample from posterior
posterior, prior = utils.sample_structure_function_ansatz(
    scales,
    mom,
    stdv,
    num_warmup=args.num_warmup,
    num_samples=args.num_samples,
    seed=args.seed,
    num_segs=args.num_segs,
    verbose=args.verbose,
    ref_scale=scales[-1],
    mean_logamp=np.log(mom[-1]), ### FIXME! 
    stdv_logamp=1.0,
    **args.prior_kwarg
)

#------------------------

# save data
utils.write_structure_function_samples(
    args.outpath,
    posterior,
    prior,
    scales,
    mom,
    stdv,
    index=args.index,
    long_or_trsv=args.long_or_trsv,
    dat=args.dat,
    min_rtol=args.min_rtol,
    min_atol=args.min_atol,
    num_warmup=args.num_warmup,
    num_samples=args.num_samples,
    seed=args.seed,
    num_segs=args.num_segs,
    verbose=args.verbose,
)
