#!/usr/bin/env python3

"""a quick script to sample from the She-Leveque scaling-exponent ansatz
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import numpy as np

from argparse import ArgumentParser

### non-standard libraries
import utils

#-------------------------------------------------

parser = ArgumentParser()

parser.add_argument("paths", nargs="+", type=str)

parser.add_argument('--ref-scale', nargs=2, type=float, required=True)

parser.add_argument('--num-warmup', default=1000, type=int)
parser.add_argument('--num-samples', default=10000, type=int)
parser.add_argument('--seed', default=[], type=int, action='append', required=True)
parser.add_argument('--num-segs', default=1, type=int)

parser.add_argument('--prior-kwarg', nargs=2, type=str, default=[], action='append')

parser.add_argument('-v', '--verbose', default=False, action='store_true')
parser.add_argument('-V', '--Verbose', default=False, action='store_true')

parser.add_argument('--outpath', default='sample-structure-function.hdf', type=str)

args = parser.parse_args()

args.prior_kwarg = dict((k, float(v)) for k, v in args.prior_kwarg)

args.verbose |= args.Verbose

#-------------------------------------------------

# load independent fits
indep_posterior = dict()
for path in args.paths:
    posterior, _, _, meta = utils.load_structure_function_samples(path, verbose=args.Verbose)
    indep_posterior[meta['index']] = posterior

indexes = np.array(sorted(indep_posterior.keys()), dtype=int)

#------------------------

posterior, prior = utils.simple_sample_scaling_exponent_ansatz(
    indexes,
    indep_posterior,
    args.ref_scale,
    num_warmup=args.num_warmup,
    num_samples=args.num_samples,
    seed=args.seed,
    num_segs=args.num_segs,
    verbose=args.verbose,
    **args.prior_kwarg
)

#------------------------

# save data
utils.write_structure_function_samples(
    args.outpath,
    posterior,
    prior,
    paths=args.paths,
    ref_scale=args.ref_scale,
    num_warmup=args.num_warmup,
    num_samples=args.num_samples,
    seed=args.seed,
    num_segs=args.num_segs,
    verbose=args.verbose,
    **args.prior_kwarg
)
