#!/usr/bin/env python3

"""a quick script to sample from the She-Leveque scaling-exponent ansatz
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

from argparse import ArgumentParser

### non-standard libraries
import utils

#-------------------------------------------------

parser = ArgumentParser()

parser.add_argument("paths", nargs="+", type=str)

parser.add_argument('--num-warmup', default=1000, type=int)
parser.add_argument('--num-samples', default=10000, type=int)
parser.add_argument('--seed', default=[], type=int, action='append', required=True)
parser.add_argument('--num-segs', default=1, type=int)

parser.add_argument('--prior-kwarg', nargs=2, type=str, default=[], action='append')

parser.add_argument('-v', '--verbose', default=False, action='store_true')
parser.add_argument('-V', '--Verbose', default=False, action='store_true')

parser.add_argument('--outpath', default='sample-structure-function.hdf', type=str)

args = parser.parse_args()

args.prior_kwarg = dict((k, float(v)) for k, v in args.prior_kwarg)

args.verbose |= args.Verbose

#-------------------------------------------------

raise NotImplementedError('''
load data
pass to some fitting function from utils
    --> build KDE internally, etc
save samples to disk
''')
