#!/bin/bash

# a quick script to average structure functions over snapshots and then make a plot
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

FLOWS=()

for M in "05" "2" "4" "10"
do
    for MA in "01" "05" "1" "2" "4" "6" "8" "10"
    do
        FLOWS+=(M${M}MA${MA})
    done
done

#-------------------------------------------------

for FLOW in ${FLOWS[@]}
do
    for FIELD in dens vel vort mag curr
    do
        for METHOD in dsf wsf
        do

            ARGS=""
            for SNAP in $(seq 50 100)
            do
                ARGS="$ARGS ${FLOW}/*${SNAP}/${FLOW}_*${SNAP}_${FIELD}_${METHOD}.hdf"
            done

            TARGET="${FLOW}/${FLOW}_avrg_${FIELD}_${METHOD}.hdf"

#            echo \
            w4t-average-structure-function \
                $ARGS \
                $TARGET \
                --verbose \
            || exit 1

#            echo \
            w4t-plot-structure-function \
                --source average $TARGET \
                --linestyle average solid \
                --marker average o \
                --title "$FLOW $FIELD $METHOD average" \
                --Verbose \
                --output-dir $FLOW \
                --tag ${FLOW}_avrg_${FIELD}_${METHOD} \
            || exit 1

#                --normalize-scale 128 \

        done
    done
done
