#!/usr/bin/env python3

"""a quick script to set up an inference that approximates scaling exponent uncertainty with a Gaussian
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import numpy as np

import h5py

import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt
plt.rcParams['text.usetex'] = True

import corner

#-----------

import jax
from jax import random
from jax import numpy as jnp
    
import numpyro
import numpyro.distributions as dist
from numpyro.infer import (MCMC, NUTS, init_to_value)
from numpyro.diagnostics import effective_sample_size

numpyro.enable_x64() # improve default numerical precision

#------------

from w4t.utils import io
from w4t.utils import infer

#-------------------------------------------------

keys = ['C0', 'beta', 'x']

min_scale = 16 # used to define bounds of averaged scaling exponent integral
max_scale = 64

prior_kwargs = dict()

#---

num_warmup  =   5000 # used to configure sampler
num_samples = 200000

seeds = [
    (123, 'b', 'r'),
    (456, 'c', 'm'),
    (789, 'cornflowerblue', 'orange'),
]

#-------------------------------------------------

def thin(samples, keys, verbose=True):
    min_neff = np.inf
    for k in keys:
        num_samples = len(samples[k])
        neff = effective_sample_size(samples[k].reshape((1,num_samples)))
        if verbose:
            print('>>> neff(%s) = %.3f' % (k, neff))
        min_neff = min(neff, min_neff)
    if verbose:
        print('min neff = %.3f' % min_neff)

    skip = int(np.ceil(num_samples/min_neff))
    if verbose:
        print('retaining 1 out of every %d steps --> %d samples' % (skip, num_samples/skip))
    return dict((k, v[::-skip][::-1]) for k, v in samples.items()) # do this fancy indexing to prefer later samples over earlier samples

#-------------------------------------------------

# set up model
def xcb_prior(
        min_C0=-1.0,
        max_C0=+4.0,
        min_x=-1.0,
        max_x=+3.0,
        min_beta=+0.0,
        max_beta=+1.0,
        **ignored
    ):
    x = numpyro.sample('x', dist.Uniform(min_x, max_x))
    C0 = numpyro.sample('C0', dist.Uniform(min_C0, max_C0))
    beta = numpyro.sample('beta', dist.Uniform(min_beta, max_beta))
    return x, C0, beta

#---

def xcb_posterior_gaussian(index, mean, stdv, **prior_kwargs):
    x, C0, beta = xcb_prior(**prior_kwargs)                 # sample from prior
    xi = infer.scaling_exponent_ansatz(index, x, C0, beta)  # compute means
    numpyro.sample('data', dist.Normal(xi, stdv), obs=mean) # condition on data

def xcb_posterior_kde(index, grids, kdes, **prior_kwargs):
    x, C0, beta = xcb_prior(**prior_kwargs)                 # sample from prior
    xi = infer.scaling_exponent_ansatz(index, x, C0, beta)  # compute means
    for ind, i in enumerate(index): # this shouldn't be too bad, but may need to vmap
        numpyro.factor('data_%d'%i, jnp.log(jnp.interp(xi[ind], grids[ind], kdes[ind])))

#-------------------------------------------------          

inpaths = []

#fields = ['vel', 'mag']
fields = ['dens', 'vort', 'curr']

Ms = ['05', '2', '4', '10']
MAs = ['01', '05', '1', '2', '4', '6', '8', '10']

for field in fields:
    for M in Ms:
        for MA in MAs:
            inpaths.append((
                'M%sMA%s/M%sMA%s_avrg_%s_dsf-ansatz.hdf' % (M, MA, M, MA, field),
                'M%sMA%s %s' % (M, MA, field),
            ))

#------------------------

for inpath, title in inpaths:

    # load data
    input_post, input_prior, scales, index, kwargs = io.load_structure_function_ansatz_samples(inpath, verbose=True)

    # come up with approximations for marginal likelihoods
    mean = []
    stdv = []

    grids = []
    kdes = []

    fig = plt.figure(figsize=(4,2*len(index)))
    plt.subplots_adjust(
        left=0.10,
        right=0.95,
        bottom=0.05,
        top=0.95,
        hspace=0.50,
    )

    for ind, i in enumerate(index):
        print('    computing posterior mean, stdv for index=%d with %d samples' % (i, len(input_post[i]['amp'])))
    
        samp = infer.averaged_logarithmic_derivative_ansatz(
            min_scale,
            max_scale,
            input_post[i]['amp'],
            input_post[i]['xi'],
            input_post[i]['sl'],
            input_post[i]['bl'],
            input_post[i]['nl'],
            input_post[i]['sh'],
            input_post[i]['bh'],
            input_post[i]['nh'],
        )

        # prior for xi that we're going to undo
        # in practice, xi is constrained well compared to the mean so that weights are all about the same
        w = 1./(np.exp(0.5*(input_post[i]['xi']-0)**2/3**2) / (2*np.pi * 3**2)**0.5)
        w /= np.sum(w)

        ### simple Gaussian approximation
        m = np.sum(w*samp)             # sample mean
        s = np.sum(w*(samp-m)**2)**0.5 # sample stdv (sorta)

        mean.append(m)
        stdv.append(s)

        ### KDE of samples
        kde_stdv = 1.06 * s / len(samp)**0.2 # rule of thumb for optimal KDE bandwidth w/r/t IMSE

        grid = np.min(samp), np.max(samp)
        d = 0.5*(grid[1]-grid[0])
        grid = np.linspace(grid[0]-d, grid[1]+d, 101)
        kde = np.sum(
            [W*np.exp(-0.5*(S-grid)**2/kde_stdv**2)/(2*np.pi*kde_stdv**2)**0.5 for W, S in zip(w, samp)],
            axis=0,
        )

        grids.append(grid)
        kdes.append(kde)

        # add to sanity-check plot
        ax = plt.subplot(len(index), 1, 1+ind)

        nbins = min(100, max(10, int(0.5*len(samp)**0.5)))
        ax.hist(samp, bins=nbins, histtype='step', density=True, weights=w, alpha=0.50, label='indep')

        xlim = np.max(np.abs(mean[-1]-np.array(ax.get_xlim())))
        x = np.linspace(-xlim+mean[-1], +xlim+mean[-1], 1001)
        ax.plot(x, np.exp(-0.5*(x-mean[-1])**2/stdv[-1]**2)/(2*np.pi*stdv[-1]**2)**0.5, alpha=0.50, label='model')
        ax.set_xlim(xmin=x[0], xmax=x[-1])

        ax.plot(grid, kde, marker='.', alpha=0.50, label='kde')

        ax.set_xlabel(r'$\left<\frac{d \log S_\tau^{p=%d}}{d\log\tau}\right>$' % i)

    # cast to arrays
    mean = jnp.array(mean, dtype=float)
    stdv = jnp.array(stdv, dtype=float)

    #------------------------

    figc = None

    combined_prior = dict((k, []) for k in keys)
    combined_posterior = dict((k, []) for k in keys)

    for snd, (seed, prior_color, posterior_color) in enumerate(seeds):

        # sample from model
        print('running sampler for prior with seed=%d for %d warmup and %d samples' % (seed, num_warmup, num_samples))

        mcmc = MCMC(
            NUTS(xcb_prior),
            num_warmup=num_warmup,
            num_samples=num_samples,
        )
        mcmc.run(random.PRNGKey(seed), **prior_kwargs)
        mcmc.print_summary(exclude_deterministic=False)

        prior = mcmc.get_samples()
        prior = thin(prior, keys)

        for k in keys:
            combined_prior[k].append(prior[k])

        #---

        print('running sampler for posterior with seed=%d for %d warmup and %d samples' % (seed, num_warmup, num_samples))

#        xcb_posterior = xcb_posterior_gaussian
#        xcb_args = (index, mean, stdv)
        xcb_posterior = xcb_posterior_kde
        xcb_args = (index, grids, kdes)

        mcmc = MCMC(
            NUTS(xcb_posterior),
            num_warmup=num_warmup,
            num_samples=num_samples,
        )
        mcmc.run(random.PRNGKey(seed), *xcb_args, **prior_kwargs)
        mcmc.print_summary(exclude_deterministic=False)

        posterior = mcmc.get_samples()
        posterior = thin(posterior, keys)

        posterior.update(numpyro.infer.log_likelihood(xcb_posterior, posterior, *xcb_args, **prior_kwargs))

        for k in keys:
            combined_posterior[k].append(posterior[k])

        #---

        # save results
        outpath = inpath[:-4]+'-fi-%d.hdf' % seed

        print('writing samples to: '+outpath)

        with h5py.File(outpath, 'w') as obj:
            obj.attrs.create('inpath', inpath)
            obj.attrs.create('num_warmup', num_warmup)
            obj.attrs.create('num_samples', num_samples)
            obj.attrs.create('seed', seed)
            for k, v in prior_kwargs.items():
                obj.attrs.create(k, v)

            grp = obj.create_group('prior')
            for k, v in prior.items():
                grp.create_dataset(k, data=v)

            grp = obj.create_group('posterior')
            for k, v in posterior.items():
                grp.create_dataset(k, data=v)

        #------------------------

        # plot results

        ### corner plot
        figc = corner.corner(
            np.transpose([prior[k] for k in keys]),
            color=prior_color,
            labels=keys,
            show_titles=True,
            hist_kwargs=dict(density=True),
            fig=figc,
        )

        figc = corner.corner(
            np.transpose([posterior[k] for k in keys]),
            color=posterior_color,
            labels=keys,
            show_titles=True,
            hist_kwargs=dict(density=True),
            fig=figc,
        )

        figc.text(0.75, 0.90-0.05*snd, 'seed=%s\n%d samples' % (seed, len(prior[keys[0]])), color=prior_color, ha='center', va='top')
        figc.text(0.90, 0.90-0.05*snd, 'seed=%s\n%d samples' % (seed, len(posterior[keys[0]])), color=posterior_color, ha='center', va='top')

        ### inferred values of xi(p)
        for ind, i in enumerate(index):
            ax = fig.axes[ind]
            xi = infer.scaling_exponent_ansatz(i, posterior['x'], posterior['C0'], posterior['beta'])
            nbins = min(100, max(10, int(0.5*len(xi)**0.5)))
            ax.hist(xi, bins=nbins, histtype='step', density=True, alpha=0.50, label='seed=%d\n%d samples'%(seed,len(xi)))

        ### full chains
        for k in keys:
            FIG = plt.figure()
            ax = FIG.gca()

            ax.plot(posterior[k], alpha=0.75)

            ax.set_xlim(xmin=0, xmax=len(posterior[k]))
            ax.set_ylabel(k)

            ax.set_title(title)

            figname = outpath[:-4]+'-%s.png' % k
            print('saving: '+figname)
            FIG.savefig(figname)
            plt.close(FIG)

    for k in keys:
        combined_prior[k] = np.concatenate(tuple(combined_prior[k]))
        combined_posterior[k] = np.concatenate(tuple(combined_posterior[k]))

    # save results
    outpath = inpath[:-4]+'-fi-combined.hdf'
            
    print('writing samples to: '+outpath)
            
    with h5py.File(outpath, 'w') as obj:
        obj.attrs.create('inpath', inpath)
        obj.attrs.create('num_warmup', num_warmup)
        obj.attrs.create('num_samples', num_samples)
        for k, v in prior_kwargs.items():
            obj.attrs.create(k, v)
    
        grp = obj.create_group('prior')
        for k, v in combined_prior.items():
            grp.create_dataset(k, data=v)
            
        grp = obj.create_group('posterior')
        for k, v in combined_posterior.items():
            grp.create_dataset(k, data=v)

    # add combined prior and posterior to corner plot
    figc = corner.corner(
        np.transpose([combined_prior[k] for k in keys]),
        color='g',
        labels=keys,
        show_titles=True,
        hist_kwargs=dict(density=True),
        fig=figc,
    )

    figc = corner.corner(
        np.transpose([combined_posterior[k] for k in keys]),
        color='k',
        labels=keys,
        show_titles=True,
        hist_kwargs=dict(density=True),
        fig=figc,
    )

    # add combined posterior for xi
    for ind, i in enumerate(index):
        ax = fig.axes[ind]
        xi = infer.scaling_exponent_ansatz(
            i,
            combined_posterior['x'],
            combined_posterior['C0'],
            combined_posterior['beta'],
        )
        nbins = min(100, max(10, int(0.5*len(xi)**0.5)))
        ax.hist(xi, bins=nbins, histtype='step', density=True, color='k', label='combined\n%d samples'%(len(xi)))

    # decorate and save
    fig.axes[0].legend(loc='upper left', ncol=3)

    for ax in list(fig.axes) + list(figc.axes):
        ax.tick_params(
            left=True,
            right=True,
            top=True,
            bottom=True,
            direction='in',
            which='both',
        )

    fig.suptitle(title)

    figname = inpath[:-4]+'-fi-xi.png'
    print('saving: '+figname)
    fig.savefig(figname)
    plt.close(fig)

    figc.suptitle(title)

    figname = inpath[:-4]+'-fi-corner.png'
    print('saving: '+figname)
    figc.savefig(figname)
    plt.close(figc)
