#!/bin/bash

# a simple script to launch scripts
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

BASEDIR="/fs/lustre/project/plasmaastro/jbeattie/turbulent_boxes/"

#-------------------------------------------------

FLOWS=()

for M in "05" "2" "4" "10"
do
    for MA in "01" "05" "1" "2" "4" "6" "8" "10"
    do
        FLOWS+=(M${M}MA${MA})
    done
done

#FLOWS+=(M6MA01)
#FLOWS+=(M6MA05)
#FLOWS+=(M6MA1)

#-------------------------------------------------

for FLOW in ${FLOWS[@]}
do
    for SNAP in $(ls ${FLOW})
    do
        for FIELD in dens vel vort mag curr
	do
	    for METHOD in dsf wsf
            do

	        SCRIPT="${FLOW}/${SNAP}/${FLOW}_${SNAP}_${FIELD}_${METHOD}.sh"
                echo "launching: $SCRIPT"

                echo \
                qsub ${SCRIPT} || exit 1

	    done
	done
    done
done
