#!/bin/zsh

# records command lines used to make plots
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

declare -A Mmap

Mmap[01]="0.1"
Mmap[05]="0.5"
Mmap[1]="1.0"
Mmap[2]="2.0"
Mmap[4]="4.0"
Mmap[6]="6.0"
Mmap[8]="8.0"
Mmap[10]="10.0"

#---

declare -A SCALE_TAG

SCALE_TAG[16]="016"
SCALE_TAG[32]="032"
SCALE_TAG[64]="064"
SCALE_TAG[128]="128"

#------------------------

#for FIELD in "dens" "vel" "vort" "mag" "curr"
for FIELD in "vel"
do

    for SCALE in 16 32 64 128
    do

        POST=()
        for M in "05" "2" "4" "10"
        do
            for MA in "01" "05" "1" "2" "4" "6" "8" "10"
            do
                POST+=("--posterior ${Mmap[$M]} ${Mmap[$MA]} M${M}MA${MA}/M${M}MA${MA}_avrg_${FIELD}_dsf-scaling-ansatz-${SCALE}.hdf")
            done
        done

#        echo \
        ./she-leveque-heatmap \
            ${=POST} \
            --output-dir "heatmaps" \
            --tag ${FIELD}_${SCALE_TAG[$SCALE]} \
            --verbose \
        || exit 1

    done
done
