#!/usr/bin/env python3

"""a quick script to plot heatmaps of inferred She-Leveque parameters on a grid of flow parameters
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

import os

import numpy as np

import matplotlib
matplotlib.use("Agg")
from matplotlib import pyplot as plt
plt.rcParams['text.usetex'] = True

from argparse import ArgumentParser

### non-standard libraries
from w4t.utils import io

#-------------------------------------------------

def heatmap(Ms, MAs, Zgrid, cmap='Reds', clabel=None):
    """make a heatmap of Z with corresponding colorbar
    """
    fig = plt.figure()
    ax = fig.gca()

    #---

    ax.imshow(np.transpose(Zgrid))

    for i in range(Zgrid.shape[0]):
        for j in range(Zgrid.shape[1]):
            ax.text(i, j, '%.3f' % Zgrid[i,j], ha='center', va='center', color='w')

    ax.set_xticks(range(len(Ms)), labels=['%.1f'%_ for _ in Ms])
    ax.set_xticks(range(len(MAs)), labels=['%.1f'%_ for _ in MAs])

    #---

    return fig

#-------------------------------------------------

parser = ArgumentParser()

parser.add_argument('-p', '--posterior', nargs=3, type=str,
    help='e.g., -p M MA path/to/samples.hdf')

parser.add_argument('-v', '--verbose', default=False, action='store_true')

parser.add_argument('-o', '--output-dir', default='.', type=str)
parser.add_argument('-t', '--tag', default='', type=str)

args = parser.parse_args()

os.makedirs(args.output_dir, exist_ok=True)

if args.tag:
    args.tag = "_"+args.tag

args.posterior = [(float(M), float(MA), path) for M, MA, path in args.posterior]

#-------------------------------------------------

# loading posterior and prior samples
data = dict()

Ms = set()
MAs = set()

for M, MA, path in args.sl_posteriors:
    if args.verbose:
        print("loading posterior samples for M=%.1f, MA=%1.f from %s" % (M, MA, path))

    posterior, _, scales, index, ref_scale, kwargs = io.load_scaling_exponent_ansatz_samples(path)
    data[(M, MA)] = dict(
        posterior=posterior,
        scales=scales,
        index=index,
        ref_sale=ref_scale,
        **kwargs
    )

    Ms.add(M)
    MAs.add(MA)

Ms = np.array(sorted(Ms), dtype=float)
MAs = np.array(sorted(MAs), dtype=float)

#------------------------

# iterate over keys and compute/plot some basic properties

Zgrid = np.empty((len(Ms), len(MAs)), dtype=float) # use this to generate plots

figtmp = os.path.join(args.output_dir, os.path.basename(__file__)+'_%s_%s'+args.tag+'.png')

for key in ['C0', 'beta', 'x']:
    if args.verbose:
        print('plotting: '+key) 

    #---

    # plot mean a posteriori
    if args.verbose:
        print('    mean a posterior')

    Zgrid[:] = np.nan # make sure we don't plot garbage data

    for i, M in enumerate(Ms):
        for j, MA in enumerate(MAs):
            Zgrid[i,j] = np.mean(data[(M,MA)]['posterior'][key])

    fig = heatmap(Mgrid, MAgrid, Zgrid, clabel='mean %s' % key)
    figname = figtmp % (key, 'mean')
    if args.verbose:
        print('        saving: '+figname)
    fig.savefig(figname)
    plt.close(fig)

    #---

    # plot median a posterior
    if args.verbose:
        print('    median a posterior')

    Zgrid[:] = np.nan # make sure we don't plot garbage data

    for i, M in enumerate(Ms):
        for j, MA in enumerate(MAs):
            Zgrid[i,j] = np.median(data[(M,MA)]['posterior'][key])

    fig = heatmap(Mgrid, MAgrid, Zgrid, clabel='median %s' % key)
    figname = figtmp % (key, 'mediaan')
    if args.verbose:
        print('        saving: '+figname)
    fig.savefig(figname)
    plt.close(fig)

    #---

    # plot max/mode a posterior
#    raise NotImplementedError

    #---

    # plot standard deviation a posterior
    if args.verbose:
        print('    stdv a posterior')

    Zgrid[:] = np.nan # make sure we don't plot garbage data

    for i, M in enumerate(Ms):
        for j, MA in enumerate(MAs):
            Zgrid[i,j] = np.stdv(data[(M,MA)]['posterior'][key])

    fig = heatmap(Mgrid, MAgrid, Zgrid, clabel='stdv %s' % key)
    figname = figtmp % (key, 'stdv')
    if args.verbose:
        print('        saving: '+figname)
    fig.savefig(figname)
    plt.close(fig)

    #---

    # plot 90% credible region
#    raise NotImplementedError
