#!/bin/zsh

#---

flows=(M05MA01)
snaps=(0050)

#---

fields=(dens mag curr vel vort)
#thrs=(00d00 01d00 02d00 03d00 04d00 05d00 10d00 99d00)
thrs=(01d00 02d00 03d00 04d00 05d00 10d00)

#---

methods=(dsf wsf)

#---

REF_SCALE=32

#---

for method in $methods
do

    for flow in $flows
    do

        for snap in $snaps
        do

            for field in $fields
            do

                # fit the full flow
#                echo \
                w4t-plot-structure-function-ansatz \
                    ${flow}/${snap}/${flow}_${snap}_${field}_${method}.hdf \
                    ${flow}/${snap}/${flow}_${snap}_${field}_${method}-ansatz.hdf \
                    $REF_SCALE \
                    --title "${flow}_${snap}_${field}_${method}" \
                    --output-dir "${flow}/${snap}" \
                    --tag ${flow}_${snap}_${field}_${method} \
                    --figtype png --dpi 200 \
                    --verbose \
                || exit 1

                for thr in $thrs
                do

                    # fit the coherent structures
#                    echo \
                    w4t-plot-structure-function-ansatz \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}.hdf \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise_${thr}-ansatz.hdf \
                        $REF_SCALE \
                        --title "${flow}_${snap}_${field}_${method}-${thr}" \
                        --output-dir "${flow}/${snap}" \
                        --tag ${flow}_${snap}_${field}_${method}-${thr} \
                        --figtype png --dpi 200 \
                        --verbose \
                    || exit 1 

                    #---

                    # fit the incoherent flow
#                    echo \
                    w4t-plot-structure-function-ansatz \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}-smooth.hdf \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise_${thr}-smooth-ansatz.hdf \
                        $REF_SCALE \
                        --title "${flow}_${snap}_${field}_${method}-${thr}" \
                        --output-dir "${flow}/${snap}" \
                        --tag ${flow}_${snap}_${field}_${method}-${thr} \
                        --figtype png --dpi 200 \
                        --verbose \
                    || exit 1 

                done

            done

        done

    done

done
