#!/bin/zsh

#---

flows=(M05MA01)
snaps=(0050)

#---

fields=(dens mag curr vel vort)
thrs=(00d00 01d00 02d00 03d00 04d00 05d00 10d00 99d00)

#---

methods=(dsf wsf)

#---

for method in $methods
do

    for flow in $flows
    do

        for snap in $snaps
        do

            for field in $fields
            do

                for thr in $thrs
                do

                    #echo \
                    w4t-plot-structure-function \
                        --title "${flow}_${snap}_${field}_${method}-$thr" \
                        --source full ${flow}/${snap}/${flow}_${snap}_${field}_${method}.hdf \
                        --marker full o \
                        --source inco ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}-smooth.hdf \
                        --marker inco s \
                        --source cohr ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}.hdf \
                        --marker cohr ^ \
                        --output-dir "${flow}/${snap}" \
                        --tag ${flow}_${snap}_${field}_${method}-${thr} \
                        --legend \
                        --grid \
                        --figtype png --dpi 200 \
                        --Verbose \
                    || exit 1

                done

            done

        done

    done

done
