#!/bin/zsh

#---

flows=(M05MA01) # M05MA05 M05MA10 M10MA01)
snaps=(0050)

#---

fields=(mag curr vel vort dens)

thrs=(01d00 02d00 03d00 04d00 05d00 10d00)

#---

methods=(dsf wsf)

#---

REF_SCALE=32

MAX_NUM_SAMPLES=250

#---

for method in $methods
do

    for flow in $flows
    do

        for snap in $snaps
        do

            for field in $fields
            do

                # plot the full flow
#                echo \
                w4t-plot-structure-function-ansatz \
                    ${flow}/${snap}/${flow}_${snap}_${field}_${method}.hdf \
                    ${flow}/${snap}/${flow}_${snap}_${field}_${method}-ansatz.hdf \
                    $REF_SCALE \
                    --max-num-samples $MAX_NUM_SAMPLES \
                    --title "${flow}_${snap}_${field}_${method}" \
                    --output-dir "${flow}/${snap}" \
                    --tag ${flow}_${snap}_${field}_${method} \
                    --figtype png --dpi 200 \
                    --verbose \
                || exit 1

                for thr in $thrs
                do

                    # plot the coherent structures
#                    echo \
                    w4t-plot-structure-function-ansatz \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}.hdf \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}-ansatz.hdf \
                        $REF_SCALE \
                        --max-num-samples $MAX_NUM_SAMPLES \
                        --title "${flow}_${snap}_${field}_${method}-${thr}" \
                        --output-dir "${flow}/${snap}" \
                        --tag ${flow}_${snap}_${field}_${method}-${thr} \
                        --figtype png --dpi 200 \
                        --verbose \
                    || exit 1 

                    #---

                    # plot the incoherent flow
#                    echo \
                    w4t-plot-structure-function-ansatz \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}-smooth.hdf \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}-smooth-ansatz.hdf \
                        $REF_SCALE \
                        --max-num-samples $MAX_NUM_SAMPLES \
                        --title "${flow}_${snap}_${field}_${method}-${thr}-smooth" \
                        --output-dir "${flow}/${snap}" \
                        --tag ${flow}_${snap}_${field}_${method}-${thr}-smooth \
                        --figtype png --dpi 200 \
                        --verbose \
                    || exit 1 

                    #---

                    # compare violins
#                    echo \
                    w4t-compare-structure-function-ansatz-violin \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}-ansatz.hdf \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}-ansatz.hdf \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}-smooth-ansatz.hdf \
                        --ref-scale $REF_SCALE \
                        --max-num-samples $MAX_NUM_SAMPLES \
                        --title "${flow}_${snap}_${field}_${method}-${thr}" \
                        --output-dir "${flow}/${snap}" \
                        --tag ${flow}_${snap}_${field}_${method}-${thr} \
                        --figtype png --dpi 200 \
                        --verbose \
                    || exit 1

                done

            done

        done

    done

done
