#!/bin/zsh

# a test workflow to sample She-Leveque parametrization for scaling exponent as a function of index
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

flows=(M05MA01)
snaps=(0050)

REF_SCALE=32

#---

#fields=(dens mag curr vel vort)
fields=(mag)

#---

methods=(dsf wsf)

#---

# clip the scales to avoid extreme behavior that is a bad match to the ansatz
MIN_SCALE=3
MAX_SCALE=255

#---

NUM_WARMUP=10000
NUM_SAMPLES=50000
NUM_RETAINED=5000

SEED=123

#---

for method in $methods
do

    for flow in $flows
    do

        for snap in $snaps
        do

            for field in $fields
            do

                # fit the full flow

                echo \
                w4t-corner \
                    ${flow}/${snap}/${flow}_${snap}_${field}_${method}-SLansatz-${REF_SCALE}.hdf \
                    --title ${flow}_${snap}_${field}_${method}-SLansatz-${REF_SCALE} \
                    --fields 'x' 'beta' 'C0' 'dlogSdlogs' \
                    --label 'x' '$x$' \
                    --label 'beta' '$\beta$' \
                    --label 'C0' '$C_0$' \
                    --label 'dlogSdlogs_0' "\$\xi(p=1, s=${REF_SCALE})\$" \
                    --label 'dlogSdlogs_1' "\$\xi(p=2, s=${REF_SCALE})\$" \
                    --label 'dlogSdlogs_2' "\$\xi(p=3, s=${REF_SCALE})\$" \
                    --label 'dlogSdlogs_3' "\$\xi(p=4, s=${REF_SCALE})\$" \
                    --label 'dlogSdlogs_4' "\$\xi(p=5, s=${REF_SCALE})\$" \
                    --label 'dlogSdlogs_5' "\$\xi(p=6, s=${REF_SCALE})\$" \
                    --root 'posterior' \
                    --output-dir ${flow}/${snap}/ \
                    --tag ${flow}_${snap}_${field}_${method}-SLansatz-${REF_SCALE} \
                    --figtype png --dpi 200 \
                    --verbose \
                || exit 1

                #---

#                echo \
                w4t-plot-scaling-exponent-ansatz \
                    ${flow}/${snap}/${flow}_${snap}_${field}_${method}.hdf \
                    ${flow}/${snap}/${flow}_${snap}_${field}_${method}-SLansatz-${REF_SCALE}.hdf \
                    --structure-function-samples ${flow}/${snap}/${flow}_${snap}_${field}_${method}-ansatz.hdf \
                    --max-num-samples 100 \
                    --title ${flow}_${snap}_${field}_${method}-SLansatz-${REF_SCALE} \
                    --output-dir ${flow}/${snap}/ \
                    --tag ${flow}_${snap}_${field}_${method}-SLansatz-${REF_SCALE} \
                    --figtype png --dpi 200 \
                    --Verbose \
                || exit 1 

exit 1

            done

        done

    done

done
