#!/bin/zsh

# a test workflow to sample She-Leveque parametrization for scaling exponent as a function of index
# Reed Essick (reed.essick@gmail.com)

#-------------------------------------------------

flows=(M05MA01)
snaps=(0050)

REF_SCALE=32

#---

fields=(mag curr vel vort dens)

thrs=(01d00 02d00 03d00 04d00 05d00 10d00)

#---

methods=(dsf wsf)

#---

# clip the scales to avoid extreme behavior that is a bad match to the ansatz
MIN_SCALE=1
MAX_SCALE=256

#---

NUM_WARMUP=10000
NUM_SAMPLES=10000
NUM_RETAINED=10000

SEED=123

#---

for method in $methods
do

    for flow in $flows
    do

        for snap in $snaps
        do

            for field in $fields
            do

                # fit the full flow

#                echo \
                w4t-sample-scaling-exponent-ansatz \
                    ${flow}/${snap}/${flow}_${snap}_${field}_${method}.hdf \
                    ${flow}/${snap}/${flow}_${snap}_${field}_${method}-SLansatz-${REF_SCALE}.hdf \
                    $REF_SCALE \
                    --min-scale $MIN_SCALE \
                    --max-scale $MAX_SCALE \
                    --num-warmup $NUM_WARMUP \
                    --num-samples $NUM_SAMPLES \
                    --num-retained $NUM_RETAINED \
                    --seed $SEED \
                    --verbose \
                || exit 1

                #---

                for thr in $thrs
                do

                    # fit the coherent flow

#                    echo \
                    w4t-sample-scaling-exponent-ansatz \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}.hdf \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}-SLansatz-${REF_SCALE}.hdf \
                        $REF_SCALE \ 
                        --min-scale $MIN_SCALE \
                        --max-scale $MAX_SCALE \
                        --num-warmup $NUM_WARMUP \
                        --num-samples $NUM_SAMPLES \
                        --num-retained $NUM_RETAINED \
                        --seed $SEED \
                        --verbose \
                    || exit 1

                    #---

                    # fit the incoherent flow

#                    echo \
                    w4t-sample-scaling-exponent-ansatz \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}-smooth.hdf \
                        ${flow}/${snap}/${flow}_${snap}_${field}_${method}_denoise-${thr}-smooth-SLansatz-${REF_SCALE}.hdf \
                        $REF_SCALE \ 
                        --min-scale $MIN_SCALE \
                        --max-scale $MAX_SCALE \
                        --num-warmup $NUM_WARMUP \
                        --num-samples $NUM_SAMPLES \
                        --num-retained $NUM_RETAINED \
                        --seed $SEED \
                        --verbose \
                    || exit 1

                done

            done

        done

    done

done
